name: vocare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  country_picker: ^2.0.20
  country_code_picker: ^3.0.0
  shared_preferences: ^2.2.2
  provider: ^6.0.0
  flutter_svg: ^2.0.9
  phosphor_flutter: ^1.0.0
  google_sign_in: ^6.1.5 
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/VocareIcone.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/vocare.png
    - assets/icons/home.svg
    - assets/icons/profile.svg
    - assets/img/VocareIcone.png

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
